name: demo_$(Date:yyyyMMdd)$(Rev:r)
trigger:
- manjari

pool: Default

steps:
- task: TerraformCLI
  displayName: 'Initialize Terraform'
  inputs:
    command: 'init'
    workingDirectory: '$(Build.SourcesDirectory)./file.tf' 

- task: TerraformCLI
  displayName: 'Validate Terraform'
  inputs:
    command: 'validate'
    workingDirectory: '$(Build.SourcesDirectory)./file.tf' 

- task: TerraformCLI
  displayName: 'Apply Terraform'
  inputs:
    command: 'apply'
    workingDirectory:  '$(Build.SourcesDirectory)./file.tf' 
    environmentServiceName: 'guthub-connection' 
    commandOptions: '-auto-approve'
