name: demo_$(Date:yyyyMMdd)$(Rev:r)
trigger:
- master

pool: default

steps:
  - script:
      python3 --version
    displayName: 'Install Python dependencies'

  # - checkout: self
  #   persistCredentials: true
  #   displayName: 'Checkout repository'

  - script: |
      python3 file.py
    displayName: 'Run Python Hello World'
    # knduhf
