name: demo_$(Date:yyyyMMdd)$(Rev:r)
trigger:
- manjari

pool: Default

steps:
- task: TerraformCLI@0
  displayName: 'Initialize Terraform'
  inputs:
    command: 'init'
    workingDirectory: '$(Build.SourcesDirectory)/azure' 

- task: TerraformCLI@0
  displayName: 'Validate Terraform'
  inputs:
    command: 'validate'
    workingDirectory: '$(Build.SourcesDirectory)/azure' 

- task: TerraformCLI@0
  displayName: 'Apply Terraform'
  inputs:
    command: 'apply'
    workingDirectory:  '$(Build.SourcesDirectory)/azure' 
    environmentServiceName: 'github-connection'
    commandOptions: '-auto-approve'
